
TinyPadPages = {
	"    local width, height = UIParent:GetWidth(), 120\n    local hgap, vgap = 3, 10\n    local w = (width-hgap*4)/3\n\n    for _,i in ipairs({1,3,4,5,6}) do\n        local f = getglobal(\"ChatFrame\"..i)\n        if i ~= 1 then f:ClearAllPoints() end\n        f:SetWidth(w)\n        f:SetHeight(height)\n    end\n\n    ChatFrame3:SetPoint(\"TOPLEFT\", ChatFrame1, \"TOPRIGHT\", hgap, 0)\n    ChatFrame4:SetPoint(\"TOPLEFT\", ChatFrame3, \"TOPRIGHT\", hgap, 0)\n    ChatFrame5:SetPoint(\"BOTTOMRIGHT\", ChatFrame3, \"TOP\", 0, vgap)\n    ChatFrame6:SetPoint(\"BOTTOMLEFT\", ChatFrame3, \"TOPRIGHT\", -75, vgap)\n\nWorldFrame:ClearAllPoints()\nWorldFrame:SetPoint(\"TOPLEFT\", UIParent, \"TOPLEFT\", 0, -14)\nWorldFrame:SetPoint(\"RIGHT\", UIParent, \"RIGHT\")\nWorldFrame:SetPoint(\"BOTTOM\", ChatFrame4, \"TOP\")\n", -- [1]
	"COMBAT_TEXT_UPDATE\narg2 ENCHANTMENT_ADDED\n\nUNIT_INVENTORY_CHANGED\narg2 player", -- [2]
	"local t = \"item:1234\"\nCockpit:Print(string.find(t, \"(%d+)\"))\n", -- [3]
	"\nSLASH_FRAMEID1 = \"/fid\"\nSlashCmdList[\"FRAMEID\"] = function()\n    local f = GetMouseFocus()\n    if f then ChatFrame1:AddMessage(f:GetName()) end\nend\n", -- [4]
	"\nlocal anchor = CreateFrame(\"Button\", \"AnchorEnterTest\", UIParent, \"SecureAnchorEnterTemplate\")\nanchor:SetPoint(\"TOPRIGHT\", MultiBarRightButton1, \"TOPRIGHT\")\nanchor:SetHeight(100)\nanchor:SetWidth(100)\n--anchor:SetAllPoints(MultiBarRightButton1)\n\n--local anchor = MultiBarRightButton1\n--anchor:SetAttribute(\"delayhovermap-anchor-leave\", \"1:true\")\nanchor:SetAttribute(\"*childraise-OnEnter\", true)\nanchor:SetAttribute(\"*childstate-OnEnter\", \"enter\")\nanchor:SetAttribute(\"*childstate-OnLeave\", \"leave\")\n\nlocal hdr = CreateFrame(\"Frame\", \"AnchorEnterTest_hdr\", anchor, \"SecureStateHeaderTemplate\")\nhdr:SetPoint(\"CENTER\") hdr:SetWidth(2) hdr:SetHeight(2)\nhdr:SetAttribute(\"statemap-anchor-enter\", \"1\")\nhdr:SetAttribute(\"statemap-anchor-leave\", \";\") \nhdr:SetAttribute(\"delaystatemap-anchor-leave\", \"1:0\")\nhdr:SetAttribute(\"delaytimemap-anchor-leave\",  \"1:1\")\nhdr:SetAttribute(\"delayhovermap-anchor-leave\", \"1:true\")\n\n-- and add it to the anchor\nanchor:SetAttribute(\"anchorchild\", hdr)\n\nhdr:SetAttribute(\"addchild\", MultiBarRightButton1)\nlocal _G = getfenv(0)\nfor i=2,12 do\n    local btn = _G[\"MultiBarRightButton\"..i]\n    btn:SetAttribute(\"hidestates\", 0)\n    hdr:SetAttribute(\"addchild\", btn)\nend\nfor i=1,12 do\n    local btn = _G[\"MultiBarLeftButton\"..i]\n    btn:SetAttribute(\"hidestates\", 0)\n    hdr:SetAttribute(\"addchild\", btn)\nend\n\n", -- [5]
}
TinyPadSettings = {
	["Font"] = 2,
}
